import type {Metadata} from "next";
import {Urbanist} from "next/font/google";
import "./globals.css";
import Header from "@/components/Header";
import Footer from "@/components/Footer";
import Image from "next/image";
import clsx from "clsx";

const urbanist = Urbanist({subsets: ["latin"]});

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
                                       children,
                                   }: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en" className="bg-slate-900 text-slate-100">
        <body className={clsx(urbanist.className, "absolute top-0 left-0 right-0 min-h-screen")}>
        <Header/>
        <main className='min-h-[600px]'>
            {children}
        </main>
        <Footer/>
        <div className="background-gradient absolute inset-0 -z-50 max-h-screen"/>
        <Image
            priority
            src='/bg1.jpeg'
            quality={10}
            alt='bg'
            className="absolute pointer-events-none inset-0 -z-40 h-full opacity-1 mix-blend-soft-light"
            fill
            sizes="100vw"
            style={{
                objectFit: "cover"
            }}/>
        </body>
        </html>
    );
}
